old = ['ADMINISTRATION','HEARING','TEMP HOSP OUTPATIENT','DENTAL','DRUGS NO CHEMO','DME','REGIONAL DMERCS','ENTERAL PARENTAL','E & M','MEDICAL SURGICAL','NATIONAL TEMP CODES','NAT. PRIVATE PAYER','ORTHOTICS','PROCEDURES/PROFESS','PROSTHECTICS','AMBULANCE','VISION']
new = ['ADMINISTRATIVE','CMS ASSIGNMENT OF HEARING SERVICES','CMS TEMPORARY HOSPITAL OUTPATIENT PROSPECTIVE PAYMENT SYSTEM','DENTAL PROCEDURES','DRUGS OTHER THAN CHEMOTHERAPY','DURABLE MEDICAL EQUIPMENT','DURABLE MEDICAL EQUIPMENT REGIONAL (DMERCS)','ENTERAL AND PARENTAL THERAPY','EVALUATION AND MANAGEMENT','MEDICAL AND SURGICAL SUPPLIES','NATIONAL CODES ASSIGNED BY CMS ON A TEMPORARY BASIS','NATIONAL CODES ESTABLISHED FOR PRIVATE PAYER USE','ORTHOTIC PROCEDURES','PROCEDURES/PROFESSIONAL SERVICES','PROSTHETIC PROCEDURES','TRANSPORTATION SERVICES INCLUDING AMBULANCE','VISION SERVICES']

script = ''
for o, n in zip(old, new):
	script += ("s/"+o+"/"+n+"/g; ")

script = "sed -i.bak '"+script+"' *"
print script